// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Js_exn     = require("bs-platform/lib/js/js_exn.js");
var Express    = require("bs-express/lib/js/src/express.js");
var Process    = require("process");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

var app = Express.express(/* () */0);

function makeSuccessJson() {
  var json = { };
  json["hello"] = "reason";
  return json;
}

app.use("/", (function (_, res, _$1) {
        return res.json(makeSuccessJson(/* () */0));
      }));

function onListen(port, e) {
  var exit = 0;
  var val;
  try {
    val = e;
    exit = 1;
  }
  catch (raw_exn){
    var exn = Js_exn.internalToOCamlException(raw_exn);
    if (exn[0] === Js_exn.$$Error) {
      console.log(exn[1]);
      Process.exit(1);
      return /* () */0;
    } else {
      throw exn;
    }
  }
  if (exit === 1) {
    console.log("Listening at localhost:" + Pervasives.string_of_int(port));
    return /* () */0;
  }
  
}

Express.App[/* listen */0](app, /* None */0, /* Some */[(function (param) {
          return onListen(3000, param);
        })], /* () */0);

exports.app             = app;
exports.makeSuccessJson = makeSuccessJson;
exports.onListen        = onListen;
/* app Not a pure module */
